# stages:
#   - sulvoRevenue-campaignReport

# tests:
#   stage: sulvoRevenue-campaignReport
#   image: mcr.microsoft.com/playwright:bionic
#   script:
#     - echo ${reportRuleId}
#     - cd functions
#     - npm install
#     - reportRuleId=${reportRuleId} type=${type} node scripts/sulvoRevenue/playwright.js

image: docker:latest

stages:
  - deploy

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml
